# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 02:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('meetup_id', models.CharField(max_length=50, unique=True, verbose_name='meetup ID')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('last_attended_at', models.DateField(blank=True, null=True, verbose_name='last attended at')),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None, verbose_name='groups')),
                ('meetup_metadata', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='meetup metadata')),
            ],
            options={
                'verbose_name': 'meetup user',
                'verbose_name_plural': 'meetup users',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('meetup_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.MeetupUser', verbose_name='meetup user')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkeIn'), ('facebook', 'Facebook'), ('github', 'Github'), ('bitbucket', 'Bitbucket')], max_length=100, verbose_name='site')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'social link',
                'verbose_name_plural': 'social links',
            },
        ),
    ]
