# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 02:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupuser',
            name='meetup_metadata',
        ),
        migrations.AddField(
            model_name='meetupuser',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='meetup metadata'),
        ),
    ]
