# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20151208_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetupuser',
            name='social_links',
            field=models.ManyToManyField(related_name='meetup_users', to='member.SocialLink', verbose_name='social links'),
        ),
        migrations.AddField(
            model_name='member',
            name='current_position',
            field=models.CharField(blank=True, max_length=400, verbose_name='current position'),
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.CharField(blank=True, max_length=100, verbose_name='github handle'),
        ),
    ]
