# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20151208_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkeIn URL'),
        ),
    ]
