# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 05:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_member_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='tags'),
        ),
    ]
