# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20151209_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_speaker',
            field=models.BooleanField(default=False, verbose_name='is speaker'),
        ),
    ]
