# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0008_auto_20151209_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='name')),
                ('bio', models.TextField(verbose_name='bio')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to='member.Member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'speaker profile',
                'verbose_name_plural': 'speaker profile',
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('summary', models.TextField(verbose_name='summary')),
                ('speakers', models.ManyToManyField(related_name='talks', to='member.Member', verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
            },
        ),
    ]
