# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('talks', '0002_auto_20160306_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='events.Event', verbose_name='presented at'),
        ),
    ]
