# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_auto_20160308_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='presented_on',
        ),
    ]
