# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='slug')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('location', models.CharField(max_length=500, verbose_name='location')),
            ],
            options={
                'verbose_name_plural': 'events',
                'verbose_name': 'event',
                'ordering': ('-date', 'name'),
            },
        ),
    ]
