# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(blank=True, verbose_name='contact')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total cost')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', verbose_name='slug')),
            ],
            options={
                'verbose_name': 'venue',
                'verbose_name_plural': 'venues',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='proposal',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='events.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='events.Venue', verbose_name='venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.Venue', verbose_name='venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_options',
            field=models.ManyToManyField(related_name='_event_venue_options_+', through='events.Proposal', to='events.Venue', verbose_name='venue options'),
        ),
    ]
