# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160311_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'proposal', 'verbose_name_plural': 'proposal'},
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='notes',
        ),
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.CharField(blank=True, max_length=200, verbose_name='capacity'),
        ),
        migrations.AddField(
            model_name='venue',
            name='contact',
            field=models.TextField(blank=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='venue',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
