# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160314_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ('name',), 'verbose_name': 'venue', 'verbose_name_plural': 'venues'},
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
    ]
